remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# theme: jekyll-theme-minimal
title: James Wen
description: Bookmark this to keep an eye on my project updates!
